Cshiwarale patch 1
hmcts/service-auth-provider-app pull request #535
Opened 2022-03-21 18:08 UTC by cshiwarale

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

#### If you're adding a new secret then do the following ####
Run the script in `./bin/set-secret-in-all-vaults <microservice-name>` and paste the output below
This will ensure the secret is in all the vaults it needs to be

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2022-03-21 21:13 UTC, timja requested changes
please fill out the PR template

2022-03-22 09:15 UTC, cshiwarale commented
> please fill out the PR template

PR template updated, please check

2022-03-22 09:21 UTC, timja commented
You don't appear to have done this?

```
Run the script in ./bin/set-secret-in-all-vaults <microservice-name> and paste the output
```

2022-03-22 23:22 UTC, timja approved these changes

2022-03-23 15:56 UTC, merged